export const NATIONS = [
  "Cree",
  "Ojibwe (Anishinaabe)",
  "Dene",
  "Blackfoot (Siksika)",
  "Mi'kmaq",
  "Mohawk (Kanien'keha:ka)",
  "Haida",
  "Tlingit",
  "Coast Salish",
  "Métis",
  "Inuit",
  "Inuvialuit",
  "Cherokee",
  "Navajo",
  "Lakota",
  "Dakota",
  "Algonquin",
  "First Nations",
  "Non-status",
  "Prefer not to say",
  "Other",
];

export const TREATY_TERRITORIES = [
  "Treaty 1",
  "Treaty 2",
  "Treaty 3",
  "Treaty 4",
  "Treaty 5",
  "Treaty 6",
  "Treaty 7",
  "Treaty 8",
  "Treaty 9",
  "Treaty 10",
  "Treaty 11",
  "Robinson-Superior",
  "Robinson-Huron",
  "Douglas Treaties",
  "Peace and Friendship",
  "Nunavut Agreement",
  "Unceded Territory",
  "US Reservation",
  "Other",
];

export const PRONOUNS = [
  "he/him",
  "she/her",
  "they/them",
  "he/they",
  "she/they",
  "ze/zir",
  "Prefer not to say",
  "Other",
];
