import test from 'node:test';import assert from 'node:assert/strict';
import {fixture} from './hermes-job-cleanup.test.ts';
import {CLEANUP,cleanupCanonical,cleanupDigest,createJobCleanup,type CleanupEvidence} from '../src/lib/server/hermes-job-cleanup.ts';
import * as contract from '../src/lib/server/job-cleanup-contract.ts';
test('exact 15000-character descriptions on every job are rejected during review before writes',async()=>{
 const f=fixture();for(const [path,doc]of f.docs)if(path.startsWith('jobs/'))f.put(path,{...doc.data,description:'x'.repeat(15000)});
 const before=new Map(f.docs);
 await assert.rejects(f.service.review({manifestId:CLEANUP.id},'cleanup'),/rollback.*capacity/i);
 assert.deepEqual(f.docs,before);
});
test('shared source and normalized route contract rejects conflicting identities and unsafe routes',()=>{
 const f=fixture(),id=CLEANUP.pairs[0][1],data=f.docs.get('jobs/'+id)!.data;
 assert.equal(typeof contract.cleanupJobSourceKey,'function');
 assert.equal(contract.cleanupJobSourceKey(data),contract.parseCleanupSourceKey(data.externalUrl));
 for(const field of ['externalUrl','applyUrl','applicationUrl','externalApplyUrl','sourceUrl']) assert.equal(contract.cleanupJobSourceKey({...data,[field]:'https://example.test/another-role'}),null);
 assert.equal(contract.cleanupJobSourceKey({...data,externalId:'different'}),null);
 assert.equal(contract.cleanupCanonicalRoute(id,{...data,slug:'role--'+id}),'/jobs/role--'+id);
 assert.equal(contract.cleanupCanonicalRoute(id,{...data,slug:'a'.repeat(201)}),null);
 assert.equal(contract.cleanupCanonicalRoute(id,{...data,slug:'../unsafe'}),null);
});
test('review rejects canonical source conflicts and 201-character slugs before any writes',async()=>{
 for(const extra of [{applicationUrl:'https://example.test/another-role'},{applyUrl:'https://example.test/another-role'},{slug:'a'.repeat(201)}]){
 const f=fixture(),p='jobs/'+CLEANUP.pairs[0][1];f.put(p,{...f.docs.get(p)!.data,...extra});const before=new Map(f.docs);
 await assert.rejects(f.service.review({manifestId:CLEANUP.id},'cleanup'));assert.deepEqual(f.docs,before);
 }
});
test('accepted native payloads roll back within unchanged bounds; oversized native payloads never write',async()=>{
 const {Timestamp,GeoPoint,Firestore}=await import('firebase-admin/firestore');
 const native=new Firestore({projectId:'demo-cleanup-offline'});
 try {for(const length of [5000,10000,15000]){
 const f=fixture();const typed={stamp:new Timestamp(1,17),point:new GeoPoint(1,2),bytes:Buffer.from([0,255]),ref:native.doc('unrelated/reference'),date:new Date(0)};
 for(const [path,doc]of f.docs)if(path.startsWith('jobs/'))f.put(path,{...doc.data,description:'x'.repeat(length),typed});
 const before=new Map(f.docs);let r;
 try {r=await f.service.review({manifestId:CLEANUP.id},'cleanup');}catch(error){assert.equal(length,15000);assert.match(String(error),/rollback.*capacity/i);assert.deepEqual(f.docs,before);continue;}
 assert.notEqual(length,15000);
 const applied=await f.service.apply(request(r),f.execution);
 const rr=await f.service.rollbackReview({auditId:applied.auditId},'cleanup');
 await f.service.rollback(request(rr),{...f.execution,idempotencyKey:'undo',requestHash:'b'.repeat(64)});
 for(const [path,doc]of before){assert.deepEqual(f.docs.get(path)!.data,doc.data);if(path.startsWith('jobs/'))assert.equal(f.docs.get(path)!.data.typed,typed);}
 for(const [path,doc]of f.docs)if(/^jobCleanup(Reviews|Backups|Receipts)\//.test(path))assert.ok(Buffer.byteLength(cleanupCanonical(doc.data))<=700000,path);
 }}finally {await native.terminate();}
});
test('all generated historic aliases satisfy the public resolver including normalized canonical suffixes',async()=>{
 const {resolveAliasRecord}=await import('../src/lib/server/job-aliases.ts');
 const f=fixture();for(const [old,id]of CLEANUP.pairs){const path='jobs/'+id;f.put(path,{...f.docs.get(path)!.data,slug:'canonical-role--'+id});const original=f.docs.get('jobs/'+old)!.data;f.put('posts/'+old,{...original,type:'job',orgId:CLEANUP.oldEmployer,slug:'historic-post-'+old});}
 const review=await f.service.review({manifestId:CLEANUP.id},'cleanup');await f.service.apply(request(review),f.execution);
 for(const [old,id]of CLEANUP.pairs){const alias=f.docs.get('jobAliases/'+old)!.data;assert.deepEqual(alias.slugs,[f.docs.get('jobs/'+old)!.data.slug,'historic-post-'+old]);assert.equal(resolveAliasRecord(old,alias,f.docs.get('jobs/'+id)!.data,null)?.destination,'/jobs/canonical-role--'+id);}
 for(const collection of ['jobs','posts']){const bad=fixture(),p=collection+'/'+CLEANUP.pairs[0][0];const base=bad.docs.get('jobs/'+CLEANUP.pairs[0][0])!.data;bad.put(p,{...base,...(collection==='posts'?{type:'job',orgId:CLEANUP.oldEmployer}:{}),slug:'x'.repeat(201)});const before=new Map(bad.docs);await assert.rejects(bad.service.review({manifestId:CLEANUP.id},'cleanup'),/slug/);assert.deepEqual(bad.docs,before);}
});
const request=(r:{reviewId:string;reviewToken:string;confirmation:string})=>({reviewId:r.reviewId,reviewToken:r.reviewToken,confirmation:r.confirmation});
test('receipt version drift rejects retries and rollback',async()=>{const f=fixture();const r=await f.service.review({manifestId:CLEANUP.id},'cleanup');const a=await f.service.apply(request(r),f.execution);const receipt=[...f.docs.values()].find(d=>d.path.startsWith('jobCleanupReceipts/')&&d.data.requestHash);assert.ok(receipt);f.put(receipt.path,receipt.data);await assert.rejects(f.service.apply(request(r),f.execution));await assert.rejects(f.service.rollbackReview({auditId:a.auditId},'cleanup'));});
test('feed drift during provider reconfirmation rejects the review',async()=>{const f=fixture();const path='jobs/'+CLEANUP.pairs[0][0];f.put(path,{...f.docs.get(path)!.data,feedId:'feed'});f.put('rssFeeds/feed',{employerId:CLEANUP.oldEmployer});const svc=createJobCleanup(f.port,{secret:'x'.repeat(32),now:()=>1_000_000,provider:async key=>{f.put('rssFeeds/feed',{employerId:'unrelated'});return {provider:'adp',sourceKey:key,checkedAt:1_000_000,status:/:2[0-3]$/.test(key)?'closed':'active',evidenceDigest:'a'.repeat(64)};}});await assert.rejects(svc.review({manifestId:CLEANUP.id},'cleanup'));});
test('canonical archived/deadline flags cannot qualify as active',async()=>{for(const extra of [{archivedAt:'x'},{deletedAt:'x'},{type:'event'},{expiresAt:new Date(0)}]){const f=fixture();const p='jobs/'+CLEANUP.pairs[0][1];f.put(p,{...f.docs.get(p)!.data,...extra});await assert.rejects(f.service.review({manifestId:CLEANUP.id},'cleanup'));}});
test('canonical alias/guard collision is rejected before creating alias chains',async()=>{for(const c of ['jobAliases','jobCleanupGuards']){const f=fixture();f.put(c+'/'+CLEANUP.pairs[0][1],{schemaVersion:99,active:true});await assert.rejects(f.service.review({manifestId:CLEANUP.id},'cleanup'));}});
test('manifest rejects arbitrary scopes/patches and preserves excluded jobs',async()=>{const f=fixture();await assert.rejects(f.service.review({manifestId:CLEANUP.id,patch:{}},'cleanup'));await assert.rejects(f.service.review({manifestId:'all'},'cleanup'));});
test('review binds missing posts, complete data, update version, employer and feed',async()=>{for(const drift of ['post','data','version','employer','feed']){const f=fixture();const path='jobs/'+CLEANUP.pairs[0][0];f.put(path,{...f.docs.get(path)!.data,feedId:'feed'});f.put('rssFeeds/feed',{employerId:CLEANUP.oldEmployer});const r=await f.service.review({manifestId:CLEANUP.id},'cleanup');if(drift==='post')f.put('posts/'+CLEANUP.pairs[0][0],{});if(drift==='data')f.docs.get(path)!.data.description='changed';if(drift==='version')f.put(path,f.docs.get(path)!.data);if(drift==='employer')f.put('employers/'+CLEANUP.oldEmployer,{name:'changed'});if(drift==='feed')f.put('rssFeeds/feed',{employerId:CLEANUP.oldEmployer,enabled:false});await assert.rejects(f.service.apply(request(r),f.execution));assert.ok(![...f.docs.keys()].some(p=>p.startsWith('jobCleanupBackups/')));}});
test('reference saturation and ownership ambiguity fail closed',async()=>{const f=fixture();f.state.saturate=true;await assert.rejects(f.service.review({manifestId:CLEANUP.id},'cleanup'),/saturated/);f.state.saturate=false;const path='jobs/'+CLEANUP.pairs[0][0];f.put(path,{...f.docs.get(path)!.data,orgId:CLEANUP.newEmployer});await assert.rejects(f.service.review({manifestId:CLEANUP.id},'cleanup'),/employer/);});
test('fresh ADP evidence, exact source and canonical active required',async()=>{for(const changed of [{provider:'other'},{checkedAt:0},{sourceKey:'adp:other:1'},{status:'closed'}]){const f=fixture();const svc=createJobCleanup(f.port,{secret:'x'.repeat(32),now:()=>1_000_000,provider:async key=>({provider:'adp',sourceKey:key,checkedAt:1_000_000,status:'active',evidenceDigest:'a'.repeat(64),...changed} as unknown as CleanupEvidence)});await assert.rejects(svc.review({manifestId:CLEANUP.id},'cleanup'));}const f=fixture();const r=await f.service.review({manifestId:CLEANUP.id},'cleanup');f.advance();await assert.rejects(f.service.apply(request(r),f.execution));});
test('dropped jobs, alias, backup, audit, source, receipt writes fail independent readback and retry',async()=>{for(const drop of ['jobs/','jobAliases/','jobCleanupGuards/','jobCleanupBackups/','jobCleanupAudits/','jobCleanupSources/','jobCleanupReceipts/']){const f=fixture();const r=await f.service.review({manifestId:CLEANUP.id},'cleanup');const plan=f.docs.get('jobCleanupReviews/'+r.reviewId)!.data;const writes=plan.writes as {path:string}[];if(drop==='jobCleanupBackups/'||drop==='jobCleanupAudits/')f.state.drop=drop+plan.auditId;else if(drop==='jobCleanupReceipts/')f.state.drop='jobCleanupReceipts/'+(await import('node:crypto')).createHash('sha256').update('cleanup:cleanup:one').digest('hex');else f.state.drop=writes.find(w=>w.path.startsWith(drop))!.path;await assert.rejects(f.service.apply(request(r),f.execution));await assert.rejects(f.service.apply(request(r),f.execution));}});
test('idempotent retry verifies all committed state; rollback refuses any drift',async()=>{const f=fixture();const r=await f.service.review({manifestId:CLEANUP.id},'cleanup');const a=await f.service.apply(request(r),f.execution);assert.deepEqual(await f.service.apply(request(r),f.execution),a);const path='jobs/'+CLEANUP.pairs[0][0];f.put(path,f.docs.get(path)!.data);await assert.rejects(f.service.apply(request(r),f.execution));await assert.rejects(f.service.rollbackReview({auditId:a.auditId},'cleanup'));});
test('same-data rewrite before first readback cannot be sealed as original commit',async()=>{const f=fixture();const r=await f.service.review({manifestId:CLEANUP.id},'cleanup');const read=f.port.read;let altered=false;f.port.read=async path=>{if(!altered&&path.startsWith('jobCleanupReceipts/')){altered=true;const p='jobs/'+CLEANUP.pairs[0][0];f.put(p,f.docs.get(p)!.data);}return read(path);};await assert.rejects(f.service.apply(request(r),f.execution));});
test('native typed preimages and post mirrors restore without migrating saves/applicant ownership',async()=>{const {Timestamp,GeoPoint,Firestore}=await import('firebase-admin/firestore');const native=new Firestore({projectId:'demo-cleanup-offline'});const f=fixture();const old=CLEANUP.pairs[0][0],path='jobs/'+old;const data={...f.docs.get(path)!.data,typed:{stamp:new Timestamp(1,17),point:new GeoPoint(1,2),bytes:Buffer.from([1,2]),ref:native.doc('unrelated/reference')}};f.put(path,data);f.put('posts/'+old,{...data,type:'job',orgId:CLEANUP.oldEmployer,slug:'historic-post'});f.put('saved_items/owned',{postId:old,userId:'original-owner',createdAt:new Timestamp(1,4)});const saved=f.docs.get('saved_items/owned');const r=await f.service.review({manifestId:CLEANUP.id},'cleanup');const a=await f.service.apply(request(r),f.execution);assert.equal(f.docs.get('posts/'+old)!.data.active,false);assert.deepEqual(f.docs.get('jobAliases/'+old)!.data.slugs,[data.slug,'historic-post']);const backup=f.docs.get('jobCleanupBackups/'+a.auditId)!.data.documents as Record<string,{data:{typed:{stamp:unknown;point:unknown;bytes:unknown}}}>;assert.ok(backup[path].data.typed.stamp instanceof Timestamp);assert.ok(backup[path].data.typed.point instanceof GeoPoint);assert.ok(Buffer.isBuffer(backup[path].data.typed.bytes));const rr=await f.service.rollbackReview({auditId:a.auditId},'cleanup');await f.service.rollback(request(rr),{...f.execution,idempotencyKey:'undo',requestHash:'b'.repeat(64)});assert.deepEqual(f.docs.get(path)!.data,data);assert.deepEqual(f.docs.get('saved_items/owned'),saved);assert.equal('duplicateOf' in f.docs.get('posts/'+old)!.data,false);await native.terminate();});
test('new scoped application after review rejects without moving applicant ownership',async()=>{const f=fixture();const r=await f.service.review({manifestId:CLEANUP.id},'cleanup');f.put('applications/new',{jobId:CLEANUP.pairs[0][0],employerId:CLEANUP.oldEmployer});await assert.rejects(f.service.apply(request(r),f.execution));assert.equal(f.docs.get('applications/new')!.data.employerId,CLEANUP.oldEmployer);});
test('rollback rechecks versions after rollback review and binds confirmation',async()=>{const f=fixture();const r=await f.service.review({manifestId:CLEANUP.id},'cleanup');const a=await f.service.apply(request(r),f.execution);const rr=await f.service.rollbackReview({auditId:a.auditId},'cleanup');const ex={...f.execution,idempotencyKey:'undo',requestHash:'b'.repeat(64)};await assert.rejects(f.service.rollback({...request(rr),confirmation:'yes'},ex));const path='posts/'+CLEANUP.pairs[0][0];f.put(path,{type:'job'});await assert.rejects(f.service.rollback(request(rr),ex));assert.equal(f.docs.get('jobs/'+CLEANUP.pairs[0][0])!.data.active,false);});
test('type tagged digests distinguish Timestamp-like maps, bytes, dates and absent fields',()=>{assert.notEqual(cleanupDigest({x:new Date(0)}),cleanupDigest({x:'1970-01-01T00:00:00.000Z'}));assert.notEqual(cleanupDigest({x:Buffer.from('hi')}),cleanupDigest({x:{0:104,1:105}}));assert.notEqual(cleanupDigest({}),cleanupDigest({x:null}));});
