/* eslint-disable @typescript-eslint/no-explicit-any -- emulator cron race boundary */
import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import vm from 'node:vm';import ts from 'typescript';import {randomBytes} from 'node:crypto';import {initializeApp,deleteApp} from 'firebase-admin/app';import {getFirestore} from 'firebase-admin/firestore';import * as expiry from '../src/lib/server/job-expiration.ts';
const enabled=process.env.IOPPS_TEST_EMULATORS==='true';
test('expiry cron rechecks a job edited after candidate enumeration',{skip:!enabled},async t=>{
 process.env.FIRESTORE_EMULATOR_HOST='127.0.0.1:8080';const id='demo-expjob-'+randomBytes(4).toString('hex');const app=initializeApp({projectId:id},id);const db=getFirestore(app);t.after(async()=>{await db.terminate();await deleteApp(app);});await db.doc('jobs/fixture').set({status:'active',active:true,closingDate:'2000-01-01'});let reads=0;let edited=false;
 const wrap=(q:any):any=>new Proxy(q,{get(target,prop){if(prop==='get')return async()=>{const snapshot=await target.get();if(++reads===4){await db.doc('jobs/fixture').update({closingDate:'2999-01-01'});edited=true;}return snapshot;};if(prop==='where')return(...args:any[])=>wrap(target.where(...args));const v=Reflect.get(target,prop);return typeof v==='function'?v.bind(target):v;}});
 const bridge=new Proxy(db,{get(target,prop){if(prop==='collection')return(name:string)=>wrap(target.collection(name));if(prop==='runTransaction')return(cb:any)=>target.runTransaction(async tx=>await cb(tx));const v=Reflect.get(target,prop);return typeof v==='function'?v.bind(target):v;}});
 const exports:any={};vm.runInNewContext(ts.transpileModule(readFileSync('src/app/api/cron/expire-jobs/route.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,console,Date,Promise,Error,process:{env:{CRON_SECRET:'fictional-cron'}},require:(name:string)=>{if(name==='next/server')return{NextResponse:{json:Response.json}};if(name==='@/lib/firebase-admin')return{getAdminDb:()=>bridge};if(name==='@/lib/server/job-expiration')return expiry;throw new Error(name);}});
 const response=await exports.GET(new Request('http://127.0.0.1/api/cron/expire-jobs',{headers:{authorization:'Bearer fictional-cron'}}));assert.equal(response.status,200);assert.equal(edited,true);assert.equal((await db.doc('jobs/fixture').get()).data()?.status,'active');assert.equal((await response.json()).closedJobs,0);
});
