import test from 'node:test';import assert from 'node:assert/strict';import {sourceModule} from './helpers/security-fixtures.mjs';
const fixture={id:'org',name:'Private Fictional Cafe',slug:'fictional-cafe',status:'approved',description:'Fictional',logoUrl:'https://example.invalid/logo.png',contactEmail:'fictional@example.invalid',directoryReview:{status:'pending',revision:1},ownerId:'private-owner',stripeCustomerId:'private-billing'};
async function request(kind,changes={}){
 const query={where(){return this},limit(){return this},get:async()=>({docs:[]})};
 const {GET}=sourceModule('src/app/api/org/[slug]/route.ts',{mocks:{'next/server':{NextResponse:Response},'@/lib/firebase-admin':{getAdminDb:()=>({collection:()=>query}),hasAdminRuntimeSupport:()=>true},'@/lib/local-dev-business-data':{},'@/lib/server/public-organization-resolver':{resolvePublicOrganization:async()=>({...fixture,...changes})},'@/lib/server/public-organization-jobs':{loadPublicOrganizationJobDocuments:async()=>({jobs:[],posts:[]})},'@/lib/server/partner-promotion':{withPartnerPromotion:x=>x},'@/lib/server/employer-auth':{requireEmployerContext:async()=>{if(['anonymous','revoked','suspended'].includes(kind))throw Error('Denied');return {orgId:kind==='other'?'other':'org',orgRole:kind==='member'?'member':'owner'};}}}});
 return GET(new Request('http://localhost/api/org/fictional-cafe',{headers:kind==='anonymous'?{}:{Authorization:'Bearer fictional'}}),{params:Promise.resolve({slug:'fictional-cafe'})});
}
test('pending listing has a private owner preview using the public projection',async()=>{const r=await request('owner');assert.equal(r.status,200);assert.equal(r.headers.get('cache-control'),'private, no-store');assert.equal(r.headers.get('vary'),'Authorization');const body=await r.json();assert.equal(body.ownerPreview,true);assert.equal(body.reviewStatus,'pending');assert.equal(body.org.name,fixture.name);assert.doesNotMatch(JSON.stringify(body),/private-owner|private-billing/);assert.deepEqual(body.jobs,[]);});
test('pending preview never grants anonymous, other organization, member, revoked or suspended access',async()=>{for(const kind of ['anonymous','other','member','revoked','suspended']){const r=await request(kind);assert.equal(r.status,404,kind);assert.doesNotMatch(await r.text(),/Private Fictional Cafe/);}});
test('owner cannot preview a deleted or disabled organization',async()=>{for(const fields of [{status:'deleted'},{disabled:true},{deletedAt:'stamp'},{status:'suspended'}])assert.equal((await request('owner',fields)).status,404);});
