import test from 'node:test';import assert from 'node:assert/strict';import {sourceModule} from './helpers/security-fixtures.mjs';
const flush=async()=>{await new Promise(setImmediate);await new Promise(setImmediate);};
function nodes(x,p){if(!x||typeof x!=='object')return [];return [...(p(x)?[x]:[]),...[x.props?.children].flat(Infinity).flatMap(y=>nodes(y,p))];}
function text(x){if(x===null||x===undefined||typeof x==='boolean')return '';if(typeof x!=='object')return String(x);return [x.props?.children].flat(Infinity).map(text).join('');}
async function fixture(status=201){let cursor=0;const cells=[],effects=[],requests=[];const user={uid:'owner',getIdToken:async()=> 'fictional'};const react={useState(v){const i=cursor++;if(!(i in cells))cells[i]=v;return [cells[i],next=>cells[i]=typeof next==='function'?next(cells[i]):next];},useRef(v){const i=cursor++;if(!(i in cells))cells[i]={current:v};return cells[i];},useEffect(fn){cursor++;if(!effects.length)effects.push(fn);}};const {default:Wrapper}=sourceModule('src/components/employer/TeamInvitations.tsx',{globals:{Error,window:{location:{origin:'https://example.invalid'}},fetch:(url,init)=>new Promise(resolve=>requests.push({url,init,resolve}))},mocks:{react,'@/lib/auth-context':{useAuth:()=>({user,loading:false})}}});const Form=Wrapper().type;const render=()=>{cursor=0;return Form({user});};render();effects[0]();await flush();nodes(render(),n=>n.type==='input')[0].props.onChange({target:{value:'guest@example.invalid'}});nodes(render(),n=>n.type==='form')[0].props.onSubmit({preventDefault(){}});await flush();assert.equal(requests.length,2);requests[1].resolve(Response.json({id:'new',path:'/team/invitations/accept#fictional-token',expiresAt:99999999},{status}));await flush();assert.equal(requests.length,status===201?3:2);return {render,requests};}
test('created link remains available when its follow-up list refresh fails',async()=>{const {render,requests}=await fixture();requests[2].resolve(new Response('{}',{status:503}));await flush();const field=nodes(render(),n=>n.type==='textarea'&&n.props.readOnly)[0];assert.ok(field,'successful creation must retain its private link');assert.match(field.props.value,/#fictional-token$/);});
test('delayed initial list cannot replace the post-creation list',async()=>{const {render,requests}=await fixture();requests[2].resolve(Response.json({invitations:[{id:'new',email:'guest@example.invalid',role:'member',state:'pending'}],nextCursor:null}));await flush();assert.match(text(render()),/guest@example.invalid/);requests[0].resolve(Response.json({invitations:[],nextCursor:null}));await flush();assert.match(text(render()),/guest@example.invalid/);});
test('owner invitation list exposes every page rather than silently dropping pending records',async()=>{const docs=Array.from({length:101},(_,i)=>({id:i.toString(16).padStart(64,'0'),data:()=>({email:'fictional@example.invalid',role:'member',state:i===100?'pending':'accepted',expiresAt:9999999999999})}));let limit=100,start='';const q={where(field,op,id){assert.equal(field,'orgId');assert.equal(id,'org');return this;},orderBy(){return this;},startAfter(id){start=id;return this;},limit(n){limit=n;return this;},get:async()=>({docs:docs.filter(d=>!start||d.id>start).slice(0,limit)})};const route=sourceModule('src/app/api/employer/team/invitations/route.ts',{mocks:{'next/server':{NextResponse:Response},'@/lib/firebase-admin':{getAdminDb:()=>({collection:()=>q})},'@/lib/server/employer-auth':{requireEmployerContext:async()=>({orgRole:'owner',orgId:'org'}),EmployerApiError:class extends Error{}}}});const first=await (await route.GET(new Request('https://example.invalid/api/employer/team/invitations'))).json();assert.equal(first.invitations.length,100);assert.equal(first.nextCursor,docs[99].id);const second=await (await route.GET(new Request('https://example.invalid/api/employer/team/invitations?cursor='+first.nextCursor))).json();assert.equal(second.invitations.length,1);assert.equal(second.invitations[0].state,'pending');assert.equal(second.nextCursor,null);});
test('rejected creation does not discard the existing initial invitation list',async()=>{const {render,requests}=await fixture(400);requests[0].resolve(Response.json({invitations:[{id:'existing',email:'existing@example.invalid',role:'member',state:'pending'}],nextCursor:null}));await flush();assert.match(text(render()),/existing@example.invalid/);});
