import test from 'node:test';import assert from 'node:assert/strict';import {sourceModule} from './helpers/security-fixtures.mjs';
function text(x){if(x===null||x===undefined||typeof x==='boolean')return '';if(typeof x!=='object')return String(x);return [x.props?.children].flat(Infinity).map(text).join('');}
test('actual profile hides stale private preview immediately on identity changes and omits view writes',async()=>{
 let cursor=0,user={uid:'owner',getIdToken:async()=> 'fictional'},effects=[],previousDeps=[],requests=[];const cells=[],cleanups=[];
 const hooks={useState(initial){const i=cursor++;if(!(i in cells))cells[i]=initial;return [cells[i],v=>cells[i]=typeof v==='function'?v(cells[i]):v];},useRef(initial){const i=cursor++;if(!(i in cells))cells[i]={current:initial};return cells[i];},useEffect(fn,deps){const i=cursor++;if(JSON.stringify(deps)!==JSON.stringify(previousDeps[i])){previousDeps[i]=deps;effects.push(()=>{cleanups[i]?.();cleanups[i]=fn();});}}};
 const mocks={'react':hooks,'next/navigation':{useParams:()=>({slug:'fictional'})},'next/link':()=>null,'next/image':()=>null,'@/components/AppShell':()=>null,'@/components/Avatar':()=>null,'@/lib/auth-context':{useAuth:()=>({user,loading:false})}};
 const {default:Page}=sourceModule('src/app/org/[slug]/page.tsx',{mocks,globals:{fetch:(url,init)=>new Promise(resolve=>requests.push({url,init,resolve}))}});
 const Component=Page().props.children.props.children.type;const render=()=>{cursor=0;return Component();};const flush=async()=>{await new Promise(setImmediate);await new Promise(setImmediate);};
 render();effects.splice(0).forEach(f=>f());await flush();assert.equal(requests.length,1);assert.equal(requests[0].init.headers?.Authorization,'Bearer fictional');requests[0].resolve(Response.json({org:{id:'org',slug:'fictional',name:'PRIVATE FICTIONAL CAFE'},ownerPreview:true,reviewStatus:'pending'}));await flush();assert.match(text(render()),/Owner preview/);assert.match(text(render()),/PRIVATE FICTIONAL CAFE/);assert.equal(requests.length,1,'no preview view-write');
 user={uid:'owner-b',getIdToken:async()=> 'fictional-b'};assert.doesNotMatch(text(render()),/PRIVATE FICTIONAL CAFE/);effects.splice(0).forEach(f=>f());await flush();assert.equal(requests.length,2);
 user=null;assert.doesNotMatch(text(render()),/PRIVATE FICTIONAL CAFE/);effects.splice(0).forEach(f=>f());await flush();requests[1].resolve(Response.json({org:{id:'b',name:'LATE PRIVATE B'},ownerPreview:true,reviewStatus:'pending'}));await flush();assert.doesNotMatch(text(render()),/LATE PRIVATE B|PRIVATE FICTIONAL CAFE/);assert.equal(requests[1].init.signal.aborted,true);requests[2].resolve(new Response('{}',{status:404}));await flush();assert.doesNotMatch(text(render()),/PRIVATE FICTIONAL CAFE/);
});
