import test from 'node:test';import assert from 'node:assert/strict';import {existsSync} from 'node:fs';import {sourceModule} from './helpers/security-fixtures.mjs';
const modulePath='src/lib/server/team-invitations.ts';
function fixture(){
 assert.ok(existsSync(modulePath),'Self-serve invitation service is missing');const service=sourceModule(modulePath,{globals:{Date,Error}});const rows=new Map([['users/owner',{role:'employer',orgId:'org',employerId:'org',orgRole:'owner'}],['members/owner',{orgId:'org',orgRole:'owner'}],['organizations/org',{name:'Fictional Cafe',status:'approved'}],['employers/org',{status:'approved'}],['users/guest',{role:'community',headline:'Keep this'}],['members/guest',{headline:'Keep member'}]]);
 const authRows=new Map([['owner',{uid:'owner',email:'owner@example.invalid',emailVerified:true,customClaims:{role:'employer'}}],['guest',{uid:'guest',email:'guest@example.invalid',emailVerified:true,customClaims:{role:'community'}}]]);
 const snapshot=ref=>({exists:rows.has(ref.path),data:()=>structuredClone(rows.get(ref.path))});let queue=Promise.resolve();const db={doc:path=>({path}),runTransaction(fn){const result=queue.then(async()=>{const writes=[];const tx={get:async ref=>snapshot(ref),getAll:async(...refs)=>refs.map(snapshot),set:(ref,data,options)=>writes.push(()=>rows.set(ref.path,options?.merge?{...rows.get(ref.path),...data}:data)),update:(ref,data)=>writes.push(()=>rows.set(ref.path,{...rows.get(ref.path),...data}))};const value=await fn(tx);writes.forEach(f=>f());return value;});queue=result.catch(()=>{});return result;}};
 const deps={db,auth:{getUser:async uid=>structuredClone(authRows.get(uid))},now:()=>1000};const owner={uid:'owner',orgId:'org',employerId:'org',orgRole:'owner'};return {service,rows,authRows,deps,owner};
}
test('owner creates an email-bound invite; acceptance preserves profiles and consumes it once',async()=>{const f=fixture();const invite=await f.service.createTeamInvitation(f.owner,{email:'guest@example.invalid',role:'member'},f.deps);assert.ok(invite.token);assert.ok(!JSON.stringify([...f.rows.values()]).includes(invite.token));await f.service.acceptTeamInvitation('guest',invite.token,f.deps);assert.equal(f.rows.get('users/guest').role,'community');assert.equal(f.rows.get('users/guest').headline,'Keep this');assert.equal(f.rows.get('members/guest').orgRole,'member');assert.equal(f.rows.get('members/guest').headline,'Keep member');await assert.rejects(()=>f.service.acceptTeamInvitation('guest',invite.token,f.deps));});
test('only owners create/revoke; recipient identity, state and current authority are enforced',async()=>{
 for(const scenario of ['admin-creator','owner-role','wrong-email','unverified','expired','revoked','other-org','claims-other-org','protected-role','existing-employer','disabled','owner-lost','org-disabled']){
  const f=fixture();if(scenario==='admin-creator')f.owner.orgRole='admin';const body={email:'guest@example.invalid',role:scenario==='owner-role'?'owner':'admin'};
  if(['admin-creator','owner-role'].includes(scenario)){await assert.rejects(()=>f.service.createTeamInvitation(f.owner,body,f.deps));continue;}
  const invite=await f.service.createTeamInvitation(f.owner,body,f.deps);
  if(scenario==='wrong-email')f.authRows.get('guest').email='other@example.invalid';if(scenario==='unverified')f.authRows.get('guest').emailVerified=false;if(scenario==='expired')f.deps.now=()=>999999999;
  if(scenario==='revoked')await f.service.revokeTeamInvitation(f.owner,invite.id,f.deps);
  if(scenario==='other-org')f.rows.get('members/guest').orgId='other';if(scenario==='claims-other-org')f.authRows.get('guest').customClaims.orgId='other';if(scenario==='protected-role')f.rows.get('users/guest').role='admin';if(scenario==='existing-employer')f.rows.get('users/guest').role='employer';if(scenario==='disabled')f.authRows.get('guest').disabled=true;if(scenario==='owner-lost')f.rows.get('members/owner').orgRole='member';if(scenario==='org-disabled')f.rows.get('organizations/org').disabled=true;
  await assert.rejects(()=>f.service.acceptTeamInvitation('guest',invite.token,f.deps),undefined,scenario);assert.equal(f.rows.get('users/guest').orgId,undefined,scenario);
 }
});
test('accept/revoke race grants at most one atomic membership and never replays',async()=>{const f=fixture(),invite=await f.service.createTeamInvitation(f.owner,{email:'guest@example.invalid',role:'member'},f.deps);const outcomes=await Promise.allSettled([f.service.revokeTeamInvitation(f.owner,invite.id,f.deps),f.service.acceptTeamInvitation('guest',invite.token,f.deps)]);assert.equal(outcomes[0].status,'fulfilled');assert.equal(outcomes[1].status,'rejected');assert.equal(f.rows.get('users/guest').orgId,undefined);});
