import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import http from 'node:http';
import {createRequire} from 'node:module';
import {chromium,expect} from '@playwright/test';
import {goal01BrowserOptions} from '../scripts/qa-goal01-browser-options.mjs';

for(const action of ['delete','close'])test(`Jobs row ${action}: accessible confirmation, cancel, error retry and one persisted mutation`,async()=>{
 const root=process.cwd(),require=createRequire(import.meta.url),dir=fs.mkdtempSync(path.join(process.env.TMPDIR||os.tmpdir(),'round7-actions-'));
 const out=path.resolve('reports/round7-job-actions',process.env.ROUND7_BASELINE?'red':'green',action);fs.mkdirSync(out,{recursive:true});
 const put=(name,text)=>{const p=path.join(dir,name);fs.writeFileSync(p,text);return p;};
 const auth=put('auth.js',`const user={uid:'fictional-owner',getIdToken:async()=>'fictional-token'};exports.useAuth=()=>({user});exports.auth={currentUser:user};`);
 const shells=put('shell.js',`const React=require('react');module.exports=({children})=>React.createElement('div',null,children);`);
 const link=put('link.js',`const React=require('react');module.exports=props=>React.createElement('a',props);`);
 const toast=put('toast.js',`exports.useToast=()=>({showToast:(message,type)=>window.notices.push({message,type})});`);
 const source=process.env.ROUND7_BASELINE?path.resolve('reports/round7-job-actions/before/src/app/org/dashboard/jobs/page.tsx'):path.join(root,'src/app/org/dashboard/jobs/page.tsx');
 const entry=put('entry.js',`import React from 'react';import {createRoot} from 'react-dom/client';import Page from ${JSON.stringify(source)};window.notices=[];createRoot(document.getElementById('root')).render(React.createElement(Page));`);
 const loader=put('loader.cjs',`const ts=require(${JSON.stringify(require.resolve('typescript'))});module.exports=s=>ts.transpileModule(s,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;`);
 const aliases={'next/link':link,'@/lib/auth-context':auth,'@/lib/firebase':auth,'@/lib/toast-context':toast};for(const n of ['OrgRoute','AppShell','Card','Button','OrgDashboardNav','Avatar'])aliases['@/components/'+n]=shells;aliases['@']=path.join(root,'src');
 const {webpack}=require('next/dist/compiled/webpack/webpack');await new Promise((resolve,reject)=>webpack({mode:'development',entry,devtool:false,output:{path:dir,filename:'bundle.js'},resolve:{extensions:['.tsx','.ts','.js'],modules:[path.join(root,'node_modules')],alias:aliases},module:{rules:[{test:/\.tsx?$/,exclude:/node_modules/,use:loader}]}},(e,s)=>e||s.hasErrors()?reject(e||Error(s.toString('errors-only'))):resolve()));
 const job={id:'fictional-job',title:'Fictional Cafe Assistant',status:action==='delete'?'draft':'active'},sentinel={id:'other-job',title:'Untouched Listing',status:'draft'};let jobs=[job,sentinel],rejectNext=false,release;const requests=[],nativeDialogs=[],errors=[];
 const server=http.createServer((req,res)=>{if(req.url==='/bundle.js'){res.setHeader('content-type','application/javascript; charset=utf-8');res.end(fs.readFileSync(path.join(dir,'bundle.js')));return;}if(req.url==='/api/employer/jobs'){res.setHeader('content-type','application/json');res.end(JSON.stringify({jobs}));return;}if(req.url==='/api/employer/jobs/fictional-job'){let body='';req.on('data',c=>body+=c);req.on('end',()=>{requests.push({method:req.method,body:body?JSON.parse(body):null});if(rejectNext){rejectNext=false;res.writeHead(503);res.end('Fictional service unavailable');return;}release=()=>{if(res.writableEnded)return;if(req.method==='DELETE')jobs=jobs.filter(j=>j.id!==job.id);else job.status=JSON.parse(body).status;res.setHeader('content-type','application/json');res.end('{}');};});return;}res.setHeader('content-type','text/html; charset=utf-8');res.end('<!doctype html><style>dialog::backdrop{background:#0008}dialog{max-width:28rem}button{padding:12px;margin:4px}</style><div id="root"></div><script src="/bundle.js"></script>');});
 const proxy=http.createServer((_,res)=>{res.writeHead(403);res.end();});proxy.on('connect',(_,s)=>s.destroy());await new Promise(r=>server.listen(0,'127.0.0.1',r));await new Promise(r=>proxy.listen(0,'127.0.0.1',r));let browser,page;let result;
 try{browser=await chromium.launch(goal01BrowserOptions({proxyPort:proxy.address().port,allowedPorts:[server.address().port]}));const context=await browser.newContext({serviceWorkers:'block',viewport:{width:390,height:900}});page=await context.newPage();page.on('dialog',async d=>{nativeDialogs.push(d.type());await d.dismiss();});page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}`);
 const rowButton=page.getByRole('button',{name:action==='delete'?'Delete':'Close Position',exact:true}).first();await rowButton.click();const dialog=page.getByRole('dialog');await expect(dialog).toBeVisible({timeout:2500});await expect(dialog).toContainText(job.title);assert.equal(requests.length,0);await expect(dialog.getByRole('button',{name:'Cancel',exact:true})).toBeFocused();await page.keyboard.press('Escape');await expect(dialog).not.toBeVisible();await expect(rowButton).toBeFocused();assert.equal(requests.length,0);
 await rowButton.click();await dialog.getByRole('button',{name:'Cancel',exact:true}).click();await expect(dialog).not.toBeVisible();assert.equal(requests.length,0);
 await rowButton.focus();await page.keyboard.press('Enter');await expect(dialog).toBeVisible();rejectNext=true;const confirm=dialog.getByRole('button',{name:action==='delete'?'Delete job':'Close position',exact:true});await confirm.click();await expect(dialog.getByRole('alert')).toBeVisible();assert.equal(requests.length,1);assert.equal(jobs.length,2);
 await confirm.dblclick();await expect.poll(()=>requests.length).toBe(2);await expect(confirm).toBeDisabled();await page.keyboard.press('Escape');await expect(dialog).toBeVisible();release();await expect(dialog).not.toBeVisible();assert.equal(requests.length,2);assert.deepEqual(requests[1],{method:action==='delete'?'DELETE':'PUT',body:action==='delete'?null:{status:'closed'}});assert.deepEqual(sentinel,{id:'other-job',title:'Untouched Listing',status:'draft'});
 await page.reload();await expect(page.getByRole('heading',{name:sentinel.title,exact:true})).toBeVisible();if(action==='delete')await expect(page.getByRole('heading',{name:job.title,exact:true})).toHaveCount(0);else{await expect(page.getByRole('heading',{name:job.title,exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Reopen',exact:true})).toBeVisible();}
 assert.deepEqual(nativeDialogs,[]);assert.deepEqual(errors,[]);result={status:'pass',requests,nativeDialogs,errors,jobs};
 }catch(e){result={status:'fail',message:e.message,requests,nativeDialogs,errors,jobs};throw e;}finally{if(page&&!page.isClosed())await page.screenshot({path:path.join(out,'result.png'),fullPage:true}).catch(()=>{});fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(result,null,2));if(release)release();if(browser)await browser.close();server.closeAllConnections();proxy.closeAllConnections();await new Promise(r=>server.close(r));await new Promise(r=>proxy.close(r));fs.rmSync(dir,{recursive:true,force:true});}
});
