"use client";
import { TERRITORY_OPTIONS, CHECK_OPTIONS, SUPPORT_OPTIONS, type HiringDetails } from "@/lib/job-hiring-details";
export default function HiringDetailsFields({value, onChange}: {value: HiringDetails; onChange: (value: HiringDetails) => void}) {
  const set = <K extends keyof HiringDetails>(key: K, next: HiringDetails[K]) => onChange({...value,[key]:next});
  return <fieldset className="hiring-fields"><legend>Help candidates understand this opportunity</legend><p>All fields are optional. Add the requirements and supports that actually apply to this role.</p>
    <label className="hiring-check"><input type="checkbox" checked={value.indigenousEncouraged} onChange={e=>set("indigenousEncouraged",e.target.checked)} />We welcome all applicants and encourage First Nations, Métis and Inuit candidates to apply.</label>
    <div className="hiring-fields-grid"><label>Workplace treaty / territory<select value={value.territory} onChange={e=>set("territory",e.target.value)}><option value="">Not specified</option>{TERRITORY_OPTIONS.map(t=><option key={t}>{t}</option>)}</select></label><label>Specific treaty, Nation, territory or region<input maxLength={200} value={value.territoryName} onChange={e=>set("territoryName",e.target.value)} placeholder="Optional — use the locally recognized name" /></label></div>
    <p className="text-sm">This describes the workplace location, not an applicant’s identity or eligibility. For multiple territories, list them in the specific-area field.</p>
    <div className="hiring-fields-grid">{([['criminalRecordCheck','Criminal record check (CPIC)'],['vulnerableSectorCheck','Vulnerable sector check']] as const).map(([key,label])=><label key={key}>{label}<select value={value[key]} onChange={e=>set(key,e.target.value)}>{CHECK_OPTIONS.map(v=><option value={v} key={v}>{v || "Not specified"}</option>)}</select></label>)}</div>
    <p className="text-sm">A criminal record check is a police background check. A vulnerable sector check is additional screening for eligible roles involving trust or authority over children or vulnerable people. These are different checks. Confirm the appropriate check with your police service. <a href="https://rcmp.ca/en/criminal-records/criminal-record-checks/vulnerable-sector-checks" target="_blank" rel="noopener noreferrer" className="underline">Vulnerable sector check guidance</a></p>
    <label className="hiring-check"><input type="checkbox" checked={value.driversLicense} onChange={e=>set("driversLicense",e.target.checked)} />Driver’s licence required</label>
    {value.driversLicense && <label>Licence class and driving requirements<input maxLength={100} value={value.licenceClass} onChange={e=>set("licenceClass",e.target.value)} placeholder="For example: Class 5; travel between work sites" /></label>}
    <label className="hiring-check"><input type="checkbox" checked={value.willTrain} onChange={e=>set("willTrain",e.target.checked)} />On-the-job training provided</label>
    {value.willTrain && <label>Training details<textarea maxLength={500} value={value.trainingDetails} onChange={e=>set("trainingDetails",e.target.value)} placeholder="What will you teach? Is the training paid?" /></label>}
    <div className="hiring-fields-grid"><label>Required certifications / tickets<textarea maxLength={500} value={value.certifications} onChange={e=>set("certifications",e.target.value)} placeholder="For example: First Aid; indicate required versus preferred" /></label><label>Schedule, shifts and travel<textarea maxLength={500} value={value.schedule} onChange={e=>set("schedule",e.target.value)} placeholder="Hours per week, rotation, weekends or travel expectations" /></label></div>
    <fieldset><legend>Supports offered</legend><div className="hiring-fields-grid">{SUPPORT_OPTIONS.map(option=><label key={option} className="hiring-check"><input type="checkbox" checked={value.supports.includes(option)} onChange={e=>set("supports",e.target.checked?[...value.supports,option]:value.supports.filter(s=>s!==option))} />{option}</label>)}</div></fieldset>
  </fieldset>;
}
